global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10s
  receiver: 'email'
receivers:
- name: 'email'
  email_configs:
  - to: 'daniel.hobbs1709@outlook.com'
    from: 'alertmanager@dtek.com'
    smarthost: smtp.office365.com:587
    auth_username: 'daniel.hobbs1709@outlook.com'
    auth_identity: 'daniel.hobbs1709@outlook.com'
    auth_password: 'Westham81'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']