global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email'



receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'
- name: 'email'
  email_configs:
  - to: 'daniel.hobbs1709@outlook.com'
    from: 'alertmanager@dtek.com'
    smarthost: 10.10.10.87:25
    auth_username: 'danny@dtek.com'
    auth_identity: 'danny@dtek.com'
    auth_password: 'Kerrisue1'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
